### ISSUE TITLE
Adjust CLI flags

### ISSUE THREAD

**Issue by Wolmin** [lukso-network/tools-lukso-cli#11]
## Type

Feature

## Description

Flags that are provided via CLI do not match those provided in attached `docker-compose` file. We should sync them for sake of keeping both flows synced in sense of clients working the same in both ways.

## TODOs

- [ ] Adjust flags to match `docker-compose`
- [ ] Provide only relevant flags (in case some are to be omitted when empty) during start execution
- [ ] Provide matching defaults

## Resources

None

## Known bugs & blockers

- #10 provides new logs structure, `logs` command should be adjusted since it will never provide any log, only errors

## Linked issues & PRs

None
