### ISSUE TITLE
Addressing demo suggestions

### ISSUE THREAD

**Issue by Wolmin** [lukso-network/tools-lukso-cli#17]
## Type

Refactor / Feature

## Description

There are some parts of CLI that need to be refactored, some that need to be implemented. Those include:

- [x] Changing data-directory structure
- [x] Running validator only when `--validator` flag is given during `start`
- [x] Making sure that CLI prioritizes the following order of given values: Flag value > config value > default value
- [x] Changing log subcommand names to more generic (geth -> execution etc.)
- [x] Making logging live by default
- [x] Changing name of logs folder and log file timestamps
- [x] Changing log structure
- [x] Resetting only given network data directory
- [x] Adjusting default recipients and etherbase addresses

## Resources

Link to ClickUp ticket: https://app.clickup.com/t/2znn3hc

## Known bugs & blockers

- `lukso status` results in unpredictable behaviour - needs fix

## Linked issues & PRs

None
