### ISSUE TITLE
Fighting majority clients by having a client recommendation / pre-selection

### ISSUE THREAD

**Issue by xtc0r** [lukso-network/tools-lukso-cli#207]
## Type

Feature

## Description

Currently we have with Geth and Prysm clients above 33% majority, with Geth leading the execution clients by far. This can lead to major issues for the chain when Geth or prysm have a critical bug.

## TODOs

- [ ] Recommend / Pre-select a execution and consensus client in the LUKSO-CLI
- [ ] Add client diversification stats and present it to the user during client selection
- [ ] Re-check recommendation and stats for each LUKSO-CLI release

**Comment by fhildeb** [comment]
Hey! Thanks for the feedback. This has been answered in Discord though will reference it here as well:

> We are actively considering and planning client diversity as a significant milestone for 2024. First, we need to get metrics up - similar to `clientdiversity.org`, as we can not solve a problem we can't measure. We're also in contact with 3rd-parties like staking services and Dappnode, so they run minority clients or provide new default images. 

> These steps should already level out the used client majorities, without creating huge problems for private operators. However, articles and awareness regarding this topic are definitely on our list too.

**Comment by xtc0r** [comment]
I think we should not wait and fight for something like clientdiversity.org. Turning the tide will only get more difficult because validators will not change their clients in production. Steering the people into the right direction when setting up their clients is much easier!
And we also have statistics. See the screenshot of my consensus client below. We have about 83% prysm validators. This value is quite representative as I'm connected to 84 clients and we only have some hundred nodes.

![image](https://github.com/lukso-network/tools-lukso-cli/assets/36508484/3b9147b0-4ae6-4ad9-b0ef-7269e86cafeb)

For execution client the geth share is even higher.

**Comment by JordyDutch** [comment]
@fhildeb Hey Felix, any updates on your comment about ` something like clientdiversity.org`? Any idea when it will be available? Could I help somewhere?

**Comment by fhildeb** [comment]
There is no update for client diversity analysis, as we have limited resources. It would help us if the community or group of network operators could investigate and analyze data sources- then we could create or fork a frontend like `clientdiversity.org` and dock on own metrics.

**CL Analytics Resources:**
- [Sigma Prime's Blockprint](https://blockprint.sigp.io/)
- [Miga Labs](https://migalabs.io/): [Monitoreth Dashboard](https://monitoreth.io/nodes) (uses Blockprint under the hood)
- [Rated.Network](https://www.rated.network/) (uses Blockprint under the hood)
- [Chainsafe Nodewatch](https://nodewatch.io/)

**EL Analytics Resources:**
- [Supermajority.info](https://supermajority.info/)
- [Ethernodes](https://ethernodes.org/) (deprecated)

**Research:**
- [Client Fingerprinting](https://twitter.com/sproulM_/status/1440512518242197516)

What needs to be found out:
- How is data fetched and if there is open source tooling
- What can be considered valid sources (how and why tools show different percentages)
- What needs to be operated on our side (boot node, full node with unlimited peer count, etc.)?

**Comment by fhildeb** [comment]
Update:

The network team is now investigating node monitoring and testing future forks.

There is another network crawler/analytics tool on the list:
- [Xatu](https://github.com/ethpandaops/xatu)

Updates will be shared here.
