### ISSUE TITLE
Write bash script

### ISSUE THREAD

**Issue by Wolmin** [lukso-network/tools-lukso-cli#23]
## Type

Feature

## Description

We need to provide a bash script to make sure that `lukso` CLI tool is initialized properly, with proper clients and binaries downloaded and with all directories initialized with proper permissions

## TODOs

Write a bash script that includes the following and put it under `./scripts/install.sh`:
- [ ] Check user's OS
- [ ] Download correct binary 
- [ ] Put the binary in user's PATH
- [ ] Create a `/var/run/lukso` directory with correct permissions

## Resources

ClickUp ticket: https://app.clickup.com/t/861mh14b6

## Known bugs & blockers

None

## Linked issues & PRs

None

**Comment by Hugoo** [comment]
This was done along these PRs:
https://github.com/lukso-network/tools-lukso-cli/pull/108/files

Closing
